export * from './language.type';
export * from './locale.type';
export * from './stats.type';
export * from './field.type';
export * from './opponents.type';
export * from './chars.type';
export * from './player.type';
export * from './imgur.type';
export * from './gameResult.type';
